#pragma once
#include <vector>

#include "Registers.hpp"
#include "Memory.hpp"
#include "Gameboy.hpp"

struct Instruction {
	Instruction(std::string instruction, unsigned char parameterLength, unsigned char ticks,
		void (Cpu::*fp)(std::vector<unsigned char> parms))
		: instruction(instruction), parameterLength(parameterLength), ticks(ticks), fp(fp) {

	}
	std::string instruction;
	unsigned char parameterLength;
	unsigned char ticks;
	void (Cpu::*fp)(std::vector<unsigned char> parms);
};

class Cpu {
	struct Clock {
		unsigned int m = 0;
		unsigned int t = 0;
	};

private:
	Registers registers;
	Clock clock;
	Memory* memory;
	GameboyModes gameboyMode;
	bool stopped;
	bool jumped;
	bool cbMode;
	void setRegisters();
	void generateInstructions();

	std::vector<Instruction> instructions;
	std::vector<Instruction> extInstructions;

	void reset();
	void setFlag(unsigned char flag);
	void clearFlag(unsigned char flag);
	bool checkFlag(unsigned char flag);
	void clearAllFlags();
	//General Functions
	unsigned char inc(unsigned char value);
	unsigned char dec(unsigned char value);
	unsigned char and(unsigned char v1, unsigned char v2);
	unsigned char xor(unsigned char v1, unsigned char v2);
	unsigned char or (unsigned char v1, unsigned char v2);
	unsigned char rlc(unsigned char byte);
	unsigned char rrc(unsigned char byte);
	unsigned char rl(unsigned char byte);
	unsigned char rr(unsigned char byte);
	unsigned char sla(unsigned char byte);
	unsigned char sra(unsigned char byte);
	unsigned char srl(unsigned char byte);
	unsigned char swap(unsigned char byte);
	void bit(unsigned char bit, unsigned char byte);
	unsigned char set(unsigned char bit, unsigned char byte);
	void compare(unsigned char value);
	unsigned char addCarry(unsigned char value);
	unsigned char subCarry(unsigned char value);
	unsigned char addBytes(unsigned char v1, unsigned char v2);
	unsigned char subBytes(unsigned char v1, unsigned char v2);
	unsigned short addShorts(unsigned short v1, unsigned short v2);

	void enableInterrupts();
	void disableInterrupts();

public:
	Cpu(GameboyModes gameboyMode);
	void printRegisters();
	unsigned char step();
	void linkMemory(Memory* mem) { this->memory = mem; }
	//Debug
	void runCommand(std::string command);
	
	//Instruction functions
	void nop(std::vector<unsigned char> parms);			//0x00
	void ld_bc_nn(std::vector<unsigned char> parms);	//0x01
	void ld_bcp_a(std::vector<unsigned char> parms);	//0x02
	void inc_bc(std::vector<unsigned char> parms);
	void inc_b(std::vector<unsigned char> parms);
	void dec_b(std::vector<unsigned char> parms);
	void ld_b_n(std::vector<unsigned char> parms);
	void rlca(std::vector<unsigned char> parms);
	void ld_nnp_sp(std::vector<unsigned char> parms);
	void add_hl_bc(std::vector<unsigned char> parms);
	void ld_a_bcp(std::vector<unsigned char> parms);	//0x0A
	void dec_bc(std::vector<unsigned char> parms);
	void inc_c(std::vector<unsigned char> parms);
	void dec_c(std::vector<unsigned char> parms);
	void ld_c_n(std::vector<unsigned char> parms);
	void rrca(std::vector<unsigned char> parms);
	void stop(std::vector<unsigned char> parms);		//0x10
	void ld_de_nn(std::vector<unsigned char> parms);
	void ld_dep_a(std::vector<unsigned char> parms);
	void inc_de(std::vector<unsigned char> parms);
	void inc_d(std::vector<unsigned char> parms);
	void dec_d(std::vector<unsigned char> parms);
	void ld_d_n(std::vector<unsigned char> parms);
	void rla(std::vector<unsigned char> parms);
	void jr_n(std::vector<unsigned char> parms);
	void add_hl_de(std::vector<unsigned char> parms);
	void ld_a_dep(std::vector<unsigned char> parms);	//0x1A
	void dec_de(std::vector<unsigned char> parms);
	void inc_e(std::vector<unsigned char> parms);
	void dec_e(std::vector<unsigned char> parms);
	void ld_e_n(std::vector<unsigned char> parms);
	void rra(std::vector<unsigned char> parms);
	void jr_nz_n(std::vector<unsigned char> parms);		//0x20
	void ld_hl_nn(std::vector<unsigned char> parms);
	void ldi_hl_a(std::vector<unsigned char> parms);
	void inc_hl(std::vector<unsigned char> parms);
	void inc_h(std::vector<unsigned char> parms);
	void dec_h(std::vector<unsigned char> parms);
	void ld_h_n(std::vector<unsigned char> parms);
	void daa(std::vector<unsigned char> parms);
	void jr_z_n(std::vector<unsigned char> parms);
	void add_hl_hl(std::vector<unsigned char> parms);
	void ld_a_hlpi(std::vector<unsigned char> parms);	//0x2A
	void dec_hl(std::vector<unsigned char> parms);
	void inc_l(std::vector<unsigned char> parms);
	void dec_l(std::vector<unsigned char> parms);
	void ld_l_n(std::vector<unsigned char> parms);
	void cpl(std::vector<unsigned char> parms);
	void jr_nc_n(std::vector<unsigned char> parms);		//0x30
	void ld_sp_nn(std::vector<unsigned char> parms);
	void ldd_hlp_a(std::vector<unsigned char> parms);
	void inc_sp(std::vector<unsigned char> parms);
	void inc_hlp(std::vector<unsigned char> parms);
	void dec_hlp(std::vector<unsigned char> parms);
	void ld_hlp_n(std::vector<unsigned char> parms);
	void scf(std::vector<unsigned char> parms);
	void jr_c_n(std::vector<unsigned char> parms);
	void add_hl_sp(std::vector<unsigned char> parms);
	void ld_a_hlpd(std::vector<unsigned char> parms);	//0x3A
	void dec_sp(std::vector<unsigned char> parms);
	void inc_a(std::vector<unsigned char> parms);
	void dec_a(std::vector<unsigned char> parms);
	void ld_a_n(std::vector<unsigned char> parms);
	void ccf(std::vector<unsigned char> parms);
	void ld_b_b(std::vector<unsigned char> parms);		//0x40
	void ld_b_c(std::vector<unsigned char> parms);
	void ld_b_d(std::vector<unsigned char> parms);
	void ld_b_e(std::vector<unsigned char> parms);
	void ld_b_h(std::vector<unsigned char> parms);
	void ld_b_l(std::vector<unsigned char> parms);
	void ld_b_hlp(std::vector<unsigned char> parms);
	void ld_b_a(std::vector<unsigned char> parms);
	void ld_c_b(std::vector<unsigned char> parms);
	void ld_c_c(std::vector<unsigned char> parms);
	void ld_c_d(std::vector<unsigned char> parms);		//0x4A
	void ld_c_e(std::vector<unsigned char> parms);
	void ld_c_h(std::vector<unsigned char> parms);
	void ld_c_l(std::vector<unsigned char> parms);
	void ld_c_hlp(std::vector<unsigned char> parms);
	void ld_c_a(std::vector<unsigned char> parms);
	void ld_d_b(std::vector<unsigned char> parms);		//0x50
	void ld_d_c(std::vector<unsigned char> parms);
	void ld_d_d(std::vector<unsigned char> parms);
	void ld_d_e(std::vector<unsigned char> parms);
	void ld_d_h(std::vector<unsigned char> parms);
	void ld_d_l(std::vector<unsigned char> parms);
	void ld_d_hlp(std::vector<unsigned char> parms);
	void ld_d_a(std::vector<unsigned char> parms);
	void ld_e_b(std::vector<unsigned char> parms);
	void ld_e_c(std::vector<unsigned char> parms);
	void ld_e_d(std::vector<unsigned char> parms);		//0x5A
	void ld_e_e(std::vector<unsigned char> parms);
	void ld_e_h(std::vector<unsigned char> parms);
	void ld_e_l(std::vector<unsigned char> parms);
	void ld_e_hlp(std::vector<unsigned char> parms);
	void ld_e_a(std::vector<unsigned char> parms);
	void ld_h_b(std::vector<unsigned char> parms);		//0x60
	void ld_h_c(std::vector<unsigned char> parms);
	void ld_h_d(std::vector<unsigned char> parms);
	void ld_h_e(std::vector<unsigned char> parms);
	void ld_h_h(std::vector<unsigned char> parms);
	void ld_h_l(std::vector<unsigned char> parms);
	void ld_h_hlp(std::vector<unsigned char> parms);
	void ld_h_a(std::vector<unsigned char> parms);
	void ld_l_b(std::vector<unsigned char> parms);
	void ld_l_c(std::vector<unsigned char> parms);
	void ld_l_d(std::vector<unsigned char> parms);
	void ld_l_e(std::vector<unsigned char> parms);
	void ld_l_h(std::vector<unsigned char> parms);
	void ld_l_l(std::vector<unsigned char> parms);
	void ld_l_hlp(std::vector<unsigned char> parms);
	void ld_l_a(std::vector<unsigned char> parms);		//0x6F
	void ld_hlp_b(std::vector<unsigned char> parms);
	void ld_hlp_c(std::vector<unsigned char> parms);
	void ld_hlp_d(std::vector<unsigned char> parms);
	void ld_hlp_e(std::vector<unsigned char> parms);
	void ld_hlp_h(std::vector<unsigned char> parms);
	void ld_hlp_l(std::vector<unsigned char> parms);
	void halt(std::vector<unsigned char> parms);
	void ld_hlp_a(std::vector<unsigned char> parms);
	void ld_a_b(std::vector<unsigned char> parms);
	void ld_a_c(std::vector<unsigned char> parms);
	void ld_a_d(std::vector<unsigned char> parms);
	void ld_a_e(std::vector<unsigned char> parms);
	void ld_a_h(std::vector<unsigned char> parms);
	void ld_a_l(std::vector<unsigned char> parms);
	void ld_a_hlp(std::vector<unsigned char> parms);
	void ld_a_a(std::vector<unsigned char> parms);		//0x7F
	void add_a_b(std::vector<unsigned char> parms);
	void add_a_c(std::vector<unsigned char> parms);
	void add_a_d(std::vector<unsigned char> parms);
	void add_a_e(std::vector<unsigned char> parms);
	void add_a_h(std::vector<unsigned char> parms);
	void add_a_l(std::vector<unsigned char> parms);
	void add_a_hlp(std::vector<unsigned char> parms);
	void add_a_a(std::vector<unsigned char> parms);
	void adc_a_b(std::vector<unsigned char> parms);
	void adc_a_c(std::vector<unsigned char> parms);
	void adc_a_d(std::vector<unsigned char> parms);
	void adc_a_e(std::vector<unsigned char> parms);
	void adc_a_h(std::vector<unsigned char> parms);
	void adc_a_l(std::vector<unsigned char> parms);
	void adc_a_hlp(std::vector<unsigned char> parms);
	void adc_a_a(std::vector<unsigned char> parms);		//0x8F
	void sub_b(std::vector<unsigned char> parms);
	void sub_c(std::vector<unsigned char> parms);
	void sub_d(std::vector<unsigned char> parms);
	void sub_e(std::vector<unsigned char> parms);
	void sub_h(std::vector<unsigned char> parms);
	void sub_l(std::vector<unsigned char> parms);
	void sub_hlp(std::vector<unsigned char> parms);
	void sub_a(std::vector<unsigned char> parms);
	void sbc_a_b(std::vector<unsigned char> parms);
	void sbc_a_c(std::vector<unsigned char> parms);
	void sbc_a_d(std::vector<unsigned char> parms);
	void sbc_a_e(std::vector<unsigned char> parms);
	void sbc_a_h(std::vector<unsigned char> parms);
	void sbc_a_l(std::vector<unsigned char> parms);
	void sbc_a_hlp(std::vector<unsigned char> parms);
	void sbc_a_a(std::vector<unsigned char> parms);		//0x9F
	void and_b(std::vector<unsigned char> parms);
	void and_c(std::vector<unsigned char> parms);
	void and_d(std::vector<unsigned char> parms);
	void and_e(std::vector<unsigned char> parms);
	void and_h(std::vector<unsigned char> parms);
	void and_l(std::vector<unsigned char> parms);
	void and_hlp(std::vector<unsigned char> parms);
	void and_a(std::vector<unsigned char> parms);
	void xor_b(std::vector<unsigned char> parms);
	void xor_c(std::vector<unsigned char> parms);
	void xor_d(std::vector<unsigned char> parms);
	void xor_e(std::vector<unsigned char> parms);
	void xor_h(std::vector<unsigned char> parms);
	void xor_l(std::vector<unsigned char> parms);
	void xor_hlp(std::vector<unsigned char> parms);
	void xor_a(std::vector<unsigned char> parms);		//0xAF
	void or_b(std::vector<unsigned char> parms);
	void or_c(std::vector<unsigned char> parms);
	void or_d(std::vector<unsigned char> parms);
	void or_e(std::vector<unsigned char> parms);
	void or_h(std::vector<unsigned char> parms);
	void or_l(std::vector<unsigned char> parms);
	void or_hlp(std::vector<unsigned char> parms);
	void or_a(std::vector<unsigned char> parms);
	void cp_b(std::vector<unsigned char> parms);
	void cp_c(std::vector<unsigned char> parms);
	void cp_d(std::vector<unsigned char> parms);
	void cp_e(std::vector<unsigned char> parms);
	void cp_h(std::vector<unsigned char> parms);
	void cp_l(std::vector<unsigned char> parms);
	void cp_hlp(std::vector<unsigned char> parms);
	void cp_a(std::vector<unsigned char> parms);		//0xBF
	void ret_nz(std::vector<unsigned char> parms);
	void pop_bc(std::vector<unsigned char> parms);
	void jp_nz_nn(std::vector<unsigned char> parms);
	void jp_nn(std::vector<unsigned char> parms);
	void call_nz_nn(std::vector<unsigned char> parms);
	void push_bc(std::vector<unsigned char> parms);
	void add_a_n(std::vector<unsigned char> parms);
	void rst_0(std::vector<unsigned char> parms);
	void ret_z(std::vector<unsigned char> parms);
	void ret(std::vector<unsigned char> parms);
	void jp_z_nn(std::vector<unsigned char> parms);
	void cb(std::vector<unsigned char> parms);
	void call_z_nn(std::vector<unsigned char> parms);
	void call_nn(std::vector<unsigned char> parms);
	void adc_a_n(std::vector<unsigned char> parms);
	void rst_08(std::vector<unsigned char> parms);		//0xCF
	void ret_nc(std::vector<unsigned char> parms);
	void pop_de(std::vector<unsigned char> parms);
	void jp_nc_nn(std::vector<unsigned char> parms);
	void call_nc_nn(std::vector<unsigned char> parms);
	void push_de(std::vector<unsigned char> parms);
	void sub_n(std::vector<unsigned char> parms);
	void rst_10(std::vector<unsigned char> parms);
	void ret_c(std::vector<unsigned char> parms);
	void reti(std::vector<unsigned char> parms);
	void jp_c_nn(std::vector<unsigned char> parms);
	void call_c_nn(std::vector<unsigned char> parms);
	void sbc_a_n(std::vector<unsigned char> parms);
	void rst_18(std::vector<unsigned char> parms);		//0xDF
	void ld_ffnp_a(std::vector<unsigned char> parms);
	void pop_hl(std::vector<unsigned char> parms);
	void ld_cp_a(std::vector<unsigned char> parms);
	void push_hl(std::vector<unsigned char> parms);
	void and_n(std::vector<unsigned char> parms);
	void rst_20(std::vector<unsigned char> parms);
	void add_sp_n(std::vector<unsigned char> parms);
	void jp_hlp(std::vector<unsigned char> parms);
	void ld_nnp_a(std::vector<unsigned char> parms);
	void xor_n(std::vector<unsigned char> parms);
	void rst_28(std::vector<unsigned char> parms);		//0xEF
	void ld_a_ffnp(std::vector<unsigned char> parms);
	void pop_af(std::vector<unsigned char> parms);
	void ld_a_cp(std::vector<unsigned char> parms);
	void di(std::vector<unsigned char> parms);
	void push_af(std::vector<unsigned char> parms);
	void or_n(std::vector<unsigned char> parms);
	void rst_30(std::vector<unsigned char> parms);
	void ld_hl_sp_n(std::vector<unsigned char> parms);
	void ld_sp_hl(std::vector<unsigned char> parms);
	void ld_a_nnp(std::vector<unsigned char> parms);
	void ei(std::vector<unsigned char> parms);
	void cp_n(std::vector<unsigned char> parms);
	void rst_38(std::vector<unsigned char> parms);

	void null(std::vector<unsigned char> parms);

	//Instructions accessed through CB
	void rlc_b(std::vector<unsigned char> parms);
	void rlc_c(std::vector<unsigned char> parms);
	void rlc_d(std::vector<unsigned char> parms);
	void rlc_e(std::vector<unsigned char> parms);
	void rlc_h(std::vector<unsigned char> parms);
	void rlc_l(std::vector<unsigned char> parms);
	void rlc_hlp(std::vector<unsigned char> parms);
	void rlc_a(std::vector<unsigned char> parms);
	void rrc_b(std::vector<unsigned char> parms);
	void rrc_c(std::vector<unsigned char> parms);
	void rrc_d(std::vector<unsigned char> parms);
	void rrc_e(std::vector<unsigned char> parms);
	void rrc_h(std::vector<unsigned char> parms);
	void rrc_l(std::vector<unsigned char> parms);
	void rrc_hlp(std::vector<unsigned char> parms);
	void rrc_a(std::vector<unsigned char> parms);
	void rl_b(std::vector<unsigned char> parms);
	void rl_c(std::vector<unsigned char> parms);
	void rl_d(std::vector<unsigned char> parms);
	void rl_d(std::vector<unsigned char> parms);
	void rl_e(std::vector<unsigned char> parms);
	void rl_h(std::vector<unsigned char> parms);
	void rl_l(std::vector<unsigned char> parms);
	void rl_hlp(std::vector<unsigned char> parms);
	void rl_a(std::vector<unsigned char> parms);
	void rr_b(std::vector<unsigned char> parms);
	void rr_c(std::vector<unsigned char> parms);
	void rr_d(std::vector<unsigned char> parms);
	void rr_e(std::vector<unsigned char> parms);
	void rr_h(std::vector<unsigned char> parms);
	void rr_l(std::vector<unsigned char> parms);
	void rr_hlp(std::vector<unsigned char> parms);
	void rr_a(std::vector<unsigned char> parms);
	void sla_b(std::vector<unsigned char> parms);
	void sla_c(std::vector<unsigned char> parms);
	void sla_d(std::vector<unsigned char> parms);
	void sla_e(std::vector<unsigned char> parms);
	void sla_h(std::vector<unsigned char> parms);
	void sla_l(std::vector<unsigned char> parms);
	void sla_hlp(std::vector<unsigned char> parms);
	void sla_a(std::vector<unsigned char> parms);
	void sra_b(std::vector<unsigned char> parms);
	void sra_c(std::vector<unsigned char> parms);
	void sra_d(std::vector<unsigned char> parms);
	void sra_e(std::vector<unsigned char> parms);
	void sra_h(std::vector<unsigned char> parms);
	void sra_l(std::vector<unsigned char> parms);
	void sra_hlp(std::vector<unsigned char> parms);
	void sra_a(std::vector<unsigned char> parms);
	void swap_b(std::vector<unsigned char> parms);
	void swap_c(std::vector<unsigned char> parms);
	void swap_d(std::vector<unsigned char> parms);
	void swap_e(std::vector<unsigned char> parms);
	void swap_h(std::vector<unsigned char> parms);
	void swap_l(std::vector<unsigned char> parms);
	void swap_hlp(std::vector<unsigned char> parms);
	void swap_a(std::vector<unsigned char> parms);
	void srl_b(std::vector<unsigned char> parms);
	void srl_c(std::vector<unsigned char> parms);
	void srl_d(std::vector<unsigned char> parms);
	void srl_e(std::vector<unsigned char> parms);
	void srl_h(std::vector<unsigned char> parms);
	void srl_l(std::vector<unsigned char> parms);
	void srl_hlp(std::vector<unsigned char> parms);
	void srl_a(std::vector<unsigned char> parms);
	void bit0_b(std::vector<unsigned char> parms);
	void bit0_c(std::vector<unsigned char> parms);
	void bit0_d(std::vector<unsigned char> parms);
	void bit0_e(std::vector<unsigned char> parms);
	void bit0_h(std::vector<unsigned char> parms);
	void bit0_l(std::vector<unsigned char> parms);
	void bit0_hlp(std::vector<unsigned char> parms);
	void bit0_a(std::vector<unsigned char> parms);
	void bit1_b(std::vector<unsigned char> parms);
	void bit1_c(std::vector<unsigned char> parms);
	void bit1_d(std::vector<unsigned char> parms);
	void bit1_e(std::vector<unsigned char> parms);
	void bit1_h(std::vector<unsigned char> parms);
	void bit1_l(std::vector<unsigned char> parms);
	void bit1_hlp(std::vector<unsigned char> parms);
	void bit1_a(std::vector<unsigned char> parms);
	void bit2_b(std::vector<unsigned char> parms);
	void bit2_c(std::vector<unsigned char> parms);
	void bit2_d(std::vector<unsigned char> parms);
	void bit2_e(std::vector<unsigned char> parms);
	void bit2_h(std::vector<unsigned char> parms);
	void bit2_l(std::vector<unsigned char> parms);
	void bit2_hlp(std::vector<unsigned char> parms);
	void bit2_a(std::vector<unsigned char> parms);
	void bit3_b(std::vector<unsigned char> parms);
	void bit3_c(std::vector<unsigned char> parms);
	void bit3_d(std::vector<unsigned char> parms);
	void bit3_e(std::vector<unsigned char> parms);
	void bit3_h(std::vector<unsigned char> parms);
	void bit3_l(std::vector<unsigned char> parms);
	void bit3_hlp(std::vector<unsigned char> parms);
	void bit3_a(std::vector<unsigned char> parms);
	void bit4_b(std::vector<unsigned char> parms);
	void bit4_c(std::vector<unsigned char> parms);
	void bit4_d(std::vector<unsigned char> parms);
	void bit4_e(std::vector<unsigned char> parms);
	void bit4_h(std::vector<unsigned char> parms);
	void bit4_l(std::vector<unsigned char> parms);
	void bit4_hlp(std::vector<unsigned char> parms);
	void bit4_a(std::vector<unsigned char> parms);
	void bit5_b(std::vector<unsigned char> parms);
	void bit5_c(std::vector<unsigned char> parms);
	void bit5_d(std::vector<unsigned char> parms);
	void bit5_e(std::vector<unsigned char> parms);
	void bit5_h(std::vector<unsigned char> parms);
	void bit5_l(std::vector<unsigned char> parms);
	void bit5_hlp(std::vector<unsigned char> parms);
	void bit5_a(std::vector<unsigned char> parms);
	void bit6_b(std::vector<unsigned char> parms);
	void bit6_c(std::vector<unsigned char> parms);
	void bit6_d(std::vector<unsigned char> parms);
	void bit6_e(std::vector<unsigned char> parms);
	void bit6_h(std::vector<unsigned char> parms);
	void bit6_l(std::vector<unsigned char> parms);
	void bit6_hlp(std::vector<unsigned char> parms);
	void bit6_a(std::vector<unsigned char> parms);
	void bit7_b(std::vector<unsigned char> parms);
	void bit7_c(std::vector<unsigned char> parms);
	void bit7_d(std::vector<unsigned char> parms);
	void bit7_e(std::vector<unsigned char> parms);
	void bit7_h(std::vector<unsigned char> parms);
	void bit7_l(std::vector<unsigned char> parms);
	void bit7_hlp(std::vector<unsigned char> parms);
	void bit7_a(std::vector<unsigned char> parms);
	void res0_b(std::vector<unsigned char> parms);
	void res0_c(std::vector<unsigned char> parms);
	void res0_d(std::vector<unsigned char> parms);
	void res0_e(std::vector<unsigned char> parms);
	void res0_h(std::vector<unsigned char> parms);
	void res0_l(std::vector<unsigned char> parms);
	void res0_hlp(std::vector<unsigned char> parms);
	void res0_a(std::vector<unsigned char> parms);
	void res1_b(std::vector<unsigned char> parms);
	void res1_c(std::vector<unsigned char> parms);
	void res1_d(std::vector<unsigned char> parms);
	void res1_e(std::vector<unsigned char> parms);
	void res1_h(std::vector<unsigned char> parms);
	void res1_l(std::vector<unsigned char> parms);
	void res1_hlp(std::vector<unsigned char> parms);
	void res1_a(std::vector<unsigned char> parms);
	void res2_b(std::vector<unsigned char> parms);
	void res2_c(std::vector<unsigned char> parms);
	void res2_d(std::vector<unsigned char> parms);
	void res2_e(std::vector<unsigned char> parms);
	void res2_h(std::vector<unsigned char> parms);
	void res2_l(std::vector<unsigned char> parms);
	void res2_hlp(std::vector<unsigned char> parms);
	void res2_a(std::vector<unsigned char> parms);
	void res3_b(std::vector<unsigned char> parms);
	void res3_c(std::vector<unsigned char> parms);
	void res3_d(std::vector<unsigned char> parms);
	void res3_e(std::vector<unsigned char> parms);
	void res3_h(std::vector<unsigned char> parms);
	void res3_l(std::vector<unsigned char> parms);
	void res3_hlp(std::vector<unsigned char> parms);
	void res3_a(std::vector<unsigned char> parms);
	void res4_b(std::vector<unsigned char> parms);
	void res4_c(std::vector<unsigned char> parms);
	void res4_d(std::vector<unsigned char> parms);
	void res4_e(std::vector<unsigned char> parms);
	void res4_h(std::vector<unsigned char> parms);
	void res4_l(std::vector<unsigned char> parms);
	void res4_hlp(std::vector<unsigned char> parms);
	void res4_a(std::vector<unsigned char> parms);
	void res5_b(std::vector<unsigned char> parms);
	void res5_c(std::vector<unsigned char> parms);
	void res5_d(std::vector<unsigned char> parms);
	void res5_e(std::vector<unsigned char> parms);
	void res5_h(std::vector<unsigned char> parms);
	void res5_l(std::vector<unsigned char> parms);
	void res5_hlp(std::vector<unsigned char> parms);
	void res5_a(std::vector<unsigned char> parms);
	void res6_b(std::vector<unsigned char> parms);
	void res6_c(std::vector<unsigned char> parms);
	void res6_d(std::vector<unsigned char> parms);
	void res6_e(std::vector<unsigned char> parms);
	void res6_h(std::vector<unsigned char> parms);
	void res6_l(std::vector<unsigned char> parms);
	void res6_hlp(std::vector<unsigned char> parms);
	void res6_a(std::vector<unsigned char> parms);
	void res7_b(std::vector<unsigned char> parms);
	void res7_c(std::vector<unsigned char> parms);
	void res7_d(std::vector<unsigned char> parms);
	void res7_e(std::vector<unsigned char> parms);
	void res7_h(std::vector<unsigned char> parms);
	void res7_l(std::vector<unsigned char> parms);
	void res7_hlp(std::vector<unsigned char> parms);
	void res7_a(std::vector<unsigned char> parms);
	void set0_b(std::vector<unsigned char> parms);
	void set0_c(std::vector<unsigned char> parms);
	void set0_d(std::vector<unsigned char> parms);
	void set0_e(std::vector<unsigned char> parms);
	void set0_h(std::vector<unsigned char> parms);
	void set0_l(std::vector<unsigned char> parms);
	void set0_hlp(std::vector<unsigned char> parms);
	void set0_a(std::vector<unsigned char> parms);
	void set1_b(std::vector<unsigned char> parms);
	void set1_c(std::vector<unsigned char> parms);
	void set1_d(std::vector<unsigned char> parms);
	void set1_e(std::vector<unsigned char> parms);
	void set1_h(std::vector<unsigned char> parms);
	void set1_l(std::vector<unsigned char> parms);
	void set1_hlp(std::vector<unsigned char> parms);
	void set1_a(std::vector<unsigned char> parms);
	void set2_b(std::vector<unsigned char> parms);
	void set2_c(std::vector<unsigned char> parms);
	void set2_d(std::vector<unsigned char> parms);
	void set2_e(std::vector<unsigned char> parms);
	void set2_h(std::vector<unsigned char> parms);
	void set2_l(std::vector<unsigned char> parms);
	void set2_hlp(std::vector<unsigned char> parms);
	void set2_a(std::vector<unsigned char> parms);
	void set3_b(std::vector<unsigned char> parms);
	void set3_c(std::vector<unsigned char> parms);
	void set3_d(std::vector<unsigned char> parms);
	void set3_e(std::vector<unsigned char> parms);
	void set3_h(std::vector<unsigned char> parms);
	void set3_l(std::vector<unsigned char> parms);
	void set3_hlp(std::vector<unsigned char> parms);
	void set3_a(std::vector<unsigned char> parms);
	void set4_b(std::vector<unsigned char> parms);
	void set4_c(std::vector<unsigned char> parms);
	void set4_d(std::vector<unsigned char> parms);
	void set4_e(std::vector<unsigned char> parms);
	void set4_h(std::vector<unsigned char> parms);
	void set4_l(std::vector<unsigned char> parms);
	void set4_hlp(std::vector<unsigned char> parms);
	void set4_a(std::vector<unsigned char> parms);
	void set5_b(std::vector<unsigned char> parms);
	void set5_c(std::vector<unsigned char> parms);
	void set5_d(std::vector<unsigned char> parms);
	void set5_e(std::vector<unsigned char> parms);
	void set5_h(std::vector<unsigned char> parms);
	void set5_l(std::vector<unsigned char> parms);
	void set5_hlp(std::vector<unsigned char> parms);
	void set5_a(std::vector<unsigned char> parms);
	void set6_b(std::vector<unsigned char> parms);
	void set6_c(std::vector<unsigned char> parms);
	void set6_d(std::vector<unsigned char> parms);
	void set6_e(std::vector<unsigned char> parms);
	void set6_h(std::vector<unsigned char> parms);
	void set6_l(std::vector<unsigned char> parms);
	void set6_hlp(std::vector<unsigned char> parms);
	void set6_a(std::vector<unsigned char> parms);
	void set7_b(std::vector<unsigned char> parms);
	void set7_c(std::vector<unsigned char> parms);
	void set7_d(std::vector<unsigned char> parms);
	void set7_e(std::vector<unsigned char> parms);
	void set7_h(std::vector<unsigned char> parms);
	void set7_l(std::vector<unsigned char> parms);
	void set7_hlp(std::vector<unsigned char> parms);
	void set7_a(std::vector<unsigned char> parms);
};